subinclude('///pleasings//docker')

rust_toolchain(
    name = 'toolchain',
    version = '1.60.0',
    visibility = ['PUBLIC'],
    arch = 'aarch64'
)

rust_binary(
    name = 'main',
    main = 'src/main.rs'
)